version: '3.8'

services:
  postgres:
    image: postgres:17
    env_file:
      - .env-docker
    hostname: postgres-idf-transactions-lab
    container_name: postgres-idf-transactions-lab
    ports:
      - ${SPRING_DATASOURCE_PORT:-5432}:5432
    networks:
      - main_network
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env-docker
    hostname: app-idf-transactions-lab
    container_name: app-idf-transactions-lab
    ports:
      - ${SPRING_APPLICATION_PORT:-8000}:8000
    depends_on:
      - postgres
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  db_data: